### ISSUE TITLE
Field required [type=missing, input_value={}, input_type=dict]

### ISSUE THREAD

**Issue by tim1f1** [henry-richard7/Spotify-Charts-Scraper#2]
Whenever I try running it, it always comes out like this:
> PS C:\Users\tim_f\Spotify-Charts-Scraper> py spotify_charts.py
> Traceback (most recent call last):
>   File "C:\Users\tim_f\Spotify-Charts-Scraper\spotify_charts.py", line 9, in <module>
>     spotify_settings = SpotifySettings()
>                        ^^^^^^^^^^^^^^^^^
>   File "C:\Users\tim_f\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic_settings\main.py", line 144, in __init__
>     super().__init__(
>   File "C:\Users\tim_f\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 211, in __init__
>     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> pydantic_core._pydantic_core.ValidationError: 4 validation errors for SpotifySettings
> client_id
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> client_secret
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> redirect_url
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> redirect_port
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> PS C:\Users\tim_f\Spotify-Charts-Scraper>

I've tried inputting the tokens in various formats,even directly in the spotify_charts.py file itself, but it seems to be the same result every tiem.

**Comment by henry-richard7** [comment]
Hi,

Have you created a .env file based on [example.env](https://github.com/henry-richard7/Spotify-Charts-Scraper/blob/main/example.env).

pydantic-settings requires it.

**Comment by tim1f1** [comment]
> Hi,
> 
> Have you created a .env file based on [example.env](https://github.com/henry-richard7/Spotify-Charts-Scraper/blob/main/example.env).
> 
> pydantic-settings requires it.

yes, it look slike this

> client_id=69fdc947396b45a3eeae47137e2c4c9b
> client_secret=7e0680b6039a67b0961366ece6f65655
> redirect_url=http://localhost
> redirect_port=5001

(I've altered the id/secret here slightly just for security, but that's the format it's in)

**Comment by henry-richard7** [comment]
Have u created this file in root directory  C:\Users\tim_f\Spotify-Charts-Scraper\\.env . Also make sure the file name is ".env" with no file name.

**Comment by tim1f1** [comment]
> Have u created this file in root directory C:\Users\tim_f\Spotify-Charts-Scraper\.env . Also make sure the file name is ".env" with no file name.

Yes, it's in that directory with that name

**Comment by henry-richard7** [comment]
Are trying to run spotify_charts.py directly, if so u will face this issue. You have to use this spotify_charts.py as package follow this [Notebook](https://github.com/henry-richard7/Spotify-Charts-Scraper/blob/main/Testing.ipynb)

**Comment by tim1f1** [comment]
> Are trying to run spotify_charts.py directly, if so u will face this issue. You have to use this spotify_charts.py as package follow this [Notebook](https://github.com/henry-richard7/Spotify-Charts-Scraper/blob/main/Testing.ipynb)

I tried running the notebook, here's what I got when running the "from spotify_charts import SpotifyCharts" cell

> 
> ---------------------------------------------------------------------------
> ValidationError                           Traceback (most recent call last)
> Cell In[1], line 1
> ----> 1 from spotify_charts import SpotifyCharts
> 
> File ~\Spotify-Charts-Scraper\spotify_charts.py:9
>       6 from Countries import Countries
>       7 from Settings import SpotifySettings
> ----> 9 spotify_settings = SpotifySettings()
>      11 client_id = spotify_settings.client_id
>      12 client_secret = spotify_settings.client_secret
> 
> File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic_settings\main.py:144, in BaseSettings.__init__(__pydantic_self__, _case_sensitive, _env_prefix, _env_file, _env_file_encoding, _env_ignore_empty, _env_nested_delimiter, _env_parse_none_str, _env_parse_enums, _cli_prog_name, _cli_parse_args, _cli_settings_source, _cli_parse_none_str, _cli_hide_none_type, _cli_avoid_json, _cli_enforce_required, _cli_use_class_docs_for_groups, _cli_exit_on_error, _cli_prefix, _secrets_dir, **values)
>     120 def __init__(
>     121     __pydantic_self__,
>     122     _case_sensitive: bool | None = None,
>    (...)
>     142 ) -> None:
>     143     # Uses something other than `self` the first arg to allow "self" as a settable attribute
> --> 144     super().__init__(
>     145         **__pydantic_self__._settings_build_values(
>     146             values,
>     147             _case_sensitive=_case_sensitive,
>     148             _env_prefix=_env_prefix,
>     149             _env_file=_env_file,
>     150             _env_file_encoding=_env_file_encoding,
>     151             _env_ignore_empty=_env_ignore_empty,
>     152             _env_nested_delimiter=_env_nested_delimiter,
>     153             _env_parse_none_str=_env_parse_none_str,
>     154             _env_parse_enums=_env_parse_enums,
>     155             _cli_prog_name=_cli_prog_name,
>     156             _cli_parse_args=_cli_parse_args,
>     157             _cli_settings_source=_cli_settings_source,
>     158             _cli_parse_none_str=_cli_parse_none_str,
>     159             _cli_hide_none_type=_cli_hide_none_type,
>     160             _cli_avoid_json=_cli_avoid_json,
>     161             _cli_enforce_required=_cli_enforce_required,
>     162             _cli_use_class_docs_for_groups=_cli_use_class_docs_for_groups,
>     163             _cli_exit_on_error=_cli_exit_on_error,
>     164             _cli_prefix=_cli_prefix,
>     165             _secrets_dir=_secrets_dir,
>     166         )
>     167     )
> 
> File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py:211, in BaseModel.__init__(self, **data)
>     209 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
>     210 __tracebackhide__ = True
> --> 211 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
>     212 if self is not validated_self:
>     213     warnings.warn(
>     214         'A custom validator is returning a value other than `self`.\n'
>     215         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
>     216         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
>     217         category=None,
>     218     )
> 
> ValidationError: 4 validation errors for SpotifySettings
> client_id
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> client_secret
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> redirect_url
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing
> redirect_port
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by henry-richard7** [comment]
Hi,

Sorry for late response can u check now I have missed to add `.env` in pydantic-settings.

**Comment by tim1f1** [comment]
The code no longer displays an error message, but doesn't seem to actually do anything. i.e. there's no output in the console or anything, it just goes to the next line of input.
![image](https://github.com/user-attachments/assets/8eddb3f6-117c-4087-b053-0e495d488569)

**Comment by henry-richard7** [comment]
Yes if u run just the py file it does not give u any output. Its a package, please look at this [Notebook](https://github.com/henry-richard7/Spotify-Charts-Scraper/blob/main/Testing.ipynb)

**Comment by tim1f1** [comment]
The notebook appears to be working for the song and artist charts now, but the albums chart gives an error
![image](https://github.com/user-attachments/assets/742d02e4-b4a6-407d-a6f5-f047fbd019fc)

**Comment by henry-richard7** [comment]
I have fixed it can u pull the changes and check?

**Comment by tim1f1** [comment]
Looks like it's all working now, thanks!
One question, I know how to get the notebook to scrape a specific date, is there a way to scrape a chart for multiple dates at once?

**Comment by henry-richard7** [comment]
You could use pandas date_range and use for loop to fetch for those date ranges.

**Comment by henry-richard7** [comment]
I am closing this issue as its fixed.
Thanks.
